export const forbiddenTags: Array<string> = [
    'css',
    'feed',
    'ns',
    'framework',
    'ssl',
    'cms',
    'cdn',
    'Web Server',
    'hosting',
    'javascript',
    'CDN',
    'copyright' ];

export const forbiddenTools = [
    'US Privacy User Signal Mechanism',
    'Facebook Signal',
    'Facebook Custom Audiences',
    'Global Site Tag',
    'Shopify Custom Theme',
    'Shopify Conversions',
    'Shopify US Dollar',
    'Shopify Account',
    'American Express',
    'Amazon Payments',
    'MasterCard',
    'PayPal',
    'Visa',
    'Apple Pay',
    'Facebook',
    'Really Simple Discovery',
    'Facebook Sharer',
    'Viewport Meta',
    'IPhone / Mobile Compatible',
    'Google Webmaster',
    'Google Universal Analytics',
    'Yahoo Small Business',
    'Lotame Crowd Control',
    'Typekit Async',
    'Google Analytics Classic',
    'Google Plus One Button',
    'Google Publisher Tag',
    'HubSpot Vex',
    'Hubspot Lead Flows',
    'Google Ad Partner Services',
    'Hubspot Ads',
    'Facebook Domain Insights',
    'Facebook Like Button',
    'YouTube',
    'Google Conversion Linker',
    'Google Analytics Enhanced Link Attribution',
    'Google Adsense',
    'reCAPTCHA',
    'GDPR Consent Management Platform',
    'Google Floodlight Counter',
    'reCAPTCHA v3',
    'AdRoll CMP System',
    'Workplace by Facebook',
    'Google Analytics Custom Variables',
    'Unsplash',
    'WooCommerce Add To Cart',
    'Getty Images',
    'Google Maps for Work',
    'Google Maps',
    'Visual Studio Tracking',
    'Google Maps API',
    'WebEx Panel',
    'Microdata for Google Shopping',
    'Google Analytics Event Tracking',
    'Mux',
    'Venmo',
    'Squarespace Add to Cart',
    'Cart Functionality',
    'Facebook Pixel for Shopify',
    'Cookie Notice',
    'SEO_META_DESCRIPTION',
    'Slack App',
    'Twitter App Card iPhone',
    'Fotolia',
    'Shutterstock',
    'iStockPhoto',
    'Stripe',
    'Imgix',
    'Discover',
    'JW Player Platform',
    'Google FeedProxy',
    'Google AdSense Custom Search Ads',
    'Google Adsense for Search',
    'Google Analytics Enhanced Ecommerce',
    'Optanon',
    'Mobile Optimized',
    'Google Analytics with Ad Tracking',
    'Braintree',
    'Google Trusted Store',
    'Google Customer Reviews',
    'Atlas Action Tags',
    'Facebook Reseller',
    'Google Code Prettify',
    'TidalTV',
    'Google Reseller',
    'Purch Group CMP System',
    'Google Inteactive Media Ads',
    'Google Direct',
    'Google AdSense Integrator',
    'Google Adsense Asynchronous',
    'Quantcast CMP System',
    'Are You a Human',
    'Cookie Consent by Osano',
    'Google Checkout',
    'Facebook Like Box',
    'Google Analytics Ecommerce',
    'Google Pay',
    'Google Floodlight Sales',
    'Google Chrome IE Frame',
    'ShareThis CMP System',
    'Facebook Embedded Video',
    'UK Cookie Consent',
    'Google Partners Badge',
    'Google Chrome Frame Popup',
    'Facebook Recommendations',
    'Maestro',
    'Microsoft Adcenter',
    'Google Analytics Multiple Trackers',
    'Google Analytics Anonymize IP',
    'Facebook Pixel View Content',
    'Google Analytics IP Anonymization',
    'Cloudflare Email Protection',
    'AdMeta',
    'Klarna',
    'Cookie Law Info',
    'Google Adsense for Domains',
    'Google Charts',
    'WebEx',
    'OneTrust LLC CMP System',
    'Google Consumer Surveys',
    'Map Point',
    'Facebook Login Button',
    'Google Analytics Timings',
    'DreamsTime',
    'SEO_META_KEYWORDS',
    'Google No Translate',
    'Googlebot Disallow',
    'Microsoft BingBot Disallow',
    'WebEx Link',
    'Microsoft MSNBot Disallow',
    'Google Translate Widget',
    'Bancontact',
    'Google Plus Embedded Posts',
    'Microsoft Azure Verified CDN',
    'Stocksy',
    'Admiral CMP System',
    'vooPlayer',
    'UStream',
    'AppRiver',
    'Google AdsBot Disallow',
    'Google Plus One Share Button',
    'Google Plus One Share Button',
    'MasterPass',
    'MasterPass',
    'Abandoned Cart Emails by Collect',
    'Celery',
    'Celery',
    'Google Analytics Enchanced Ecommerce Product Impression',
    'Pixabay',
    'Pixabay',
    'Google News Bot Disallow',
    'Google News Bot Disallow',
    'vimeoVHX',
    'Google AdsBot Mobile Disallow',
    'Cookie Control',
    'Cookie Control',
    'CookiePro',
    'Metomic',
    'Google / Youtube Adsense',
    'Facebook Comments',
    'Google Analytics Forced SSL',
    'Google Analytics Forced SSL',
    'Termly',
    'Google Media Partners Disallow',
    'Google Media Partners Disallow',
    'PayPal Form',
    'PayPal Form',
    'Faktor CMP System',
    'Faktor',
    'Google Call Conversion Tracking',
    'Google Call Conversion Tracking',
    'Kaltura',
    'Fastly Verified CDN',
    'Google Analytics Social Interactions',
    'Icons8',
    'CookieBAR',
    'X-Cart',
    'Google AMP Client ID',
    'Cloudflare CDN',
    'TermsFeed',
    'Google Event Calendar for Wix',
    'Cookie Trust CMP System',
    'oil.js',
    'Cookie Script',
    'In Cart UpSell',
    'SSL Google Analytics',
    'Google Sheets',
    'Google Analyticator',
    'Facebook Activity Feed',
    'Deposit Photos',
    'Skimbit CMP System',
    'Google AdsBot Mobile Apps Disallow',
    'Improve Digital International CMP System',
    'Add To Cart Booster by Codeinero',
    'vzaar',
    'Usercentrics',
    'Google Plus One Snippet',
    'ImageKit.io',
    'DocuSign',
    'Google Image Bot Disallow',
    'CartoDB',
    'Secure Privacy',
    'IpMeta',
    'Imgsafe',
    'Cloudflare Verify',
    'GDPR Cookie Compiler',
    'Google AJAX Feed API',
    'Google Audio Player',
    'CartActivity',
    'Razorpay',
    'HubSpot Analytics',
    'IcoMoon',
    'Conversant CMP System',
    'Omega Facebook Messenger',
    'Giphy',
    'Google Language Translator',
    'Google Analytics Tasks',
    'Live800',
    'Metabase',
    'Cloudflare Bot Manager',
    'Ratepay',
    'Legal Monster',
    'Easy GDPR',
    'Google Surveys',
    'Worldpay',
    'CookieYes for WordPress',
    'Google Analytics Opt-Out Privacy',
    'Cookie First',
    'Google Maps Engine',
    'Facebook Audience Network',
    'About Cookies',
    'SOCIETE CMP System',
    'Google Data Studio',
    'Google Meet',
    'Sweet Captcha',
    'consentmanager',
    'CookieYes',
    'Cookie Information',
    'UnionPay',
    'Iconfinder',
    'WooCommerce Menu Cart',
    'DocuSign CLM',
    'Google Suite',
    'Pojo Accessibility',
    'Blip TV',
    'Gumlet',
    'hCaptcha',
    'Docusign Gen',
    'Slack',
    'Google Calendar',
    'thePlatform',
    'Segment Consent Manager',
    'Livestream',
    'Accessible360',
    'Facebook Badge',
    'Google Maps Embed',
    'eSSENTIAL Accessibility',
    'Essential Accessibility',
    'Human Presence',
    'HubSpot Cookie Policy Banner',
    'Axeptio',
    'Corbis',
    'Evidon CMP System',
    'Facebook Measurement',
    'Google Funding Choices',
    'DailyMotion Video',
    'Visa Checkout',
    'TVPage',
    'Sourcepoint CMP System',
    'Offline JS',
    'Cincopa',
    'Dollar Photo Club',
    'Google Ditu',
    'Google Search Console',
    'securiti',
    'TrustArc CMP System',
    'Google Affiliate Network',
    'Facebook Customer Chat SDK',
    'Checkout.com',
    'Google Web Elements',
    'Bits on the Run',
    'Pexels',
    'Paymentus',
    'Google Play Store',
    'SagePay',
    'CookieHub',
    'Barclaycard Business',
    'Vidalytics',
    'VideoGenie',
    'uScreen',
    'Global Privacy Control',
    'Bambora',
    'Didomi',
    'Wirecard',
    'Google Cloud CDN',
    'www.shutterstock.com',
    'IconScout',
    'SFR CMP System',
    'Google Global Server Load Balancer',
    'Facebook Data Processing Options',
    'Google Universal Analytics Debug',
    'Google Gadgets',
    'BrightTALK',
    'Google Drive for Wix',
    'Facebook Messenger Platform',
    'Google Ads & Shopping for Wix',
    'Google Buzz Share',
    'Screely',
    'YourAdChoices.com',
    'CCBill',
    'Network Advertising Initiative',
    'Ketch',
    'AdChoices in Canada',
    'Geetest',
    'GourmetAds Reseller',
    'shutterstock.com',
    'Google Video Bot Disallow',
    'VioStream',
    'Cloudflare Stream',
    'PrimeBox CookieBar',
    'Cookies and You',
    'Avatars.io',
    'Picatcha',
    'BlueSnap',
    'Google AdSense for Wix',
    'aheadWorks Ajax Cart Pro',
    'Google Ad Manager',
    'Google Ad Manager',
    'Google Ad Manager',
    'Acknowledgement of Country',
    'Cloudflare Radar',
    'Cloudflare Radar Top 200k',
    'Cloudflare Radar Top 500k',
    'Accessibility Statement',
    'Corporate Governance and Regulatory Compliance',
    'Cloudflare Radar Top 50k',
    'Cookie Policy',
    'Cloudflare Radar Top 100k',
    'Gender Pay Gap',
    'Google Voice',
    'Do Not Sell',
    'Code of Conduct',
    'Diversity Equity Inclusion DEI Policy',
    'Supply Chain Policy',
    'Social Impact Policy',
    'Animal Welfare Policy',
    'Data Protection Policy'
 ];   

export const hiddenCategories: Array<string> = [
    'Copyright',
    'CSS Media Queries',
    'Document Encoding',
    'Browser Specific',
    'Compatibility',
    'CSS',
    'Design Framework',
    'DocType Declaration',
    'Meta Tags',
    'Mobile Specific',
    'SSL Seals',
    'Domain Parking',
    'Application',
    'Controls',
    'Magento Theme',
    'Node.js',
    'NodeJS',
    'PHP Theme',
    'Plugin',
    'Programming Language',
    'Schema',
    'Theme',
    'Web App',
    'WordPress Theme',
    'AJAX',
    'Animation',
    'Charting',
    'Compatibility',
    'Cookie Management',
    'Error Tracking',
    'Fingerprint',
    'fingerprinting',
    'Forms and Surveys',
    'Framework',
    'Image Library',
    'JavaScript Library',
    'jQuery Plugin',
    'Lightbox',
    'Media',
    'Slider',
    'UI',
    'Language',
    'DDoS Protection',
    'Enterprise DNS',
    'SaaS DNS',
    'Module',
    'Operating System',
    'Protocol',
    'Robots.txt',
    'SEO Header Tag',
    'SEO Meta Tag',
    'SEO Title Tag',
    'Shipping Providers',
    'Extended Validation',
    'Multi Domain',
    'Not Trusted',
    'Root Authority',
    'Server Gated Cryptography',
    'Wildcard',
    'Syndication Techniques',
    'Edge Delivery Network',
    'Advertising',
    'Bookings',
    'Homepage Link',
    'Web Master Registration',
    'Application Server',
    'Caching Proxy',
    'Linux Web Server',
    'Windows Web Server',
    'WordPress Plugins',
    'Video Players',
    'Standard',
    'Fonts',
    'Digital Video Ads',
    'Audience Targetg',
    'Facebook Exchange',
    'Data Management Platform',
    'Demand-side Platform',
    'Ad network',
    'Ad Exchange',
    'Multi-channel',
    'Payment Currency',
    'Open source',
    'Plug in / Module',
    'Transaction email',
    'Ad server',
    'Application Performance',
    'Site Search',
    'Social Sharing',
    'Business Email Hosting',
    'Fraud Prevention',
    'Transactional Email',
    'Login',
    'Visitor Count Tracking'
];

export const treckActions = [
    'addNode',
    'removeNode',
    'moveNode',
    'addArrow',
    'removeArrow'
];

export const WhitelistCategories = [
    'Marketing Automation',
    'CRM',
    'Audience Measurement',
    'Conversion Optimization',
    'A/B Testing',
    'Personalization',
    'Visitor Count Tracking'
];
