export const forbiddenTags: Array<string> = [
    'css',
    'feed',
    'ns',
    'framework',
    'ssl',
    'cms',
    'cdn',
    'Web Server',
    'hosting',
    'javascript',
    'CDN',
    'copyright' ];

export const forbiddenTools: Array<string> = [
    'US Privacy User Signal Mechanism',
    'Facebook Signal',
    'Facebook Custom Audiences',
    'Global Site Tag',
    'Shopify Custom Theme',
    'Shopify Conversions',
    'Shopify US Dollar',
    'Shopify Account',
    'American Express',
    'Amazon Payments',
    'MasterCard',
    'PayPal',
    'Visa',
    'Apple Pay' ];    

export const hiddenCategories: Array<string> = [
    'Copyright',
    'CSS Media Queries',
    'Document Encoding',
    'Browser Specific',
    'Compatibility',
    'CSS',
    'Design Framework',
    'DocType Declaration',
    'Meta Tags',
    'Mobile Specific',
    'SSL Seals',
    'Domain Parking',
    'Application',
    'Controls',
    'Magento Theme',
    'Node.js',
    'NodeJS',
    'PHP Theme',
    'Plugin',
    'Programming Language',
    'Schema',
    'Theme',
    'Web App',
    'WordPress Theme',
    'AJAX',
    'Animation',
    'Charting',
    'Compatibility',
    'Cookie Management',
    'Error Tracking',
    'Fingerprint',
    'fingerprinting',
    'Forms and Surveys',
    'Framework',
    'Image Library',
    'JavaScript Library',
    'jQuery Plugin',
    'Lightbox',
    'Media',
    'Slider',
    'UI',
    'Language',
    'DDoS Protection',
    'Enterprise DNS',
    'SaaS DNS',
    'Module',
    'Operating System',
    'Protocol',
    'Robots.txt',
    'SEO Header Tag',
    'SEO Meta Tag',
    'SEO Title Tag',
    'Shipping Providers',
    'Extended Validation',
    'Multi Domain',
    'Not Trusted',
    'Root Authority',
    'Server Gated Cryptography',
    'Wildcard',
    'Syndication Techniques',
    'Edge Delivery Network',
    'Advertising',
    'Bookings',
    'Homepage Link',
    'Web Master Registration',
    'Application Server',
    'Caching Proxy',
    'Linux Web Server',
    'Windows Web Server',
    'WordPress Plugins',
    'Video Players',
    'Standard',
    'Fonts',
    'Digital Video Ads',
    'Audience Targetg',
    'Facebook Exchange',
    'Data Management Platform',
    'Demand-side Platform',
    'Ad network',
    'Ad Exchange',
    'Multi-channel',
    'Payment Currency',
    'Open source',
    'Plug in / Module',
    'Transaction email',
    'Ad server',
    'Application Performance',
    'Site Search',
    'Social Sharing',
    'Business Email Hosting',
    'Fraud Prevention',
    'Transactional Email',
    'Login',
    'Visitor Count Tracking'
];

export const treckActions = [
    'addNode',
    'removeNode',
    'moveNode',
    'addArrow',
    'removeArrow'
];

export const WhitelistCategories = [
    'Marketing Automation',
    'CRM',
    'Audience Measurement',
    'Conversion Optimization',
    'A/B Testing',
    'Personalization',
    'Visitor Count Tracking'
];
